#!/bin/bash

dirDotfiles=~/.dotfiles/
dirConfig=${dirDotfiles}config/
dirBackup=${dirDotfiles}backup/

mkdir -p $dirBackup

# For all folders that are in the config.
for config in "$@"
do
  if [ ! -d ${dirConfig}$config ]
  then
    echo "[$config] No config file found."
    continue
  fi

  echo "[$config] Installing."
  prefix="--"
  
  if [ -e ${dirConfig}$config.pre ]
  then
    echo "[$config] Executing pre actions."
    ( sh "${dirConfig}$config.pre" )
  fi

  # Per file copying logic.
  for file in `ls -A ${dirConfig}$config`
  do
    # Backup.
    if [ -e ~/.$file -o -h ~/.$file ]
    then
      # Remove backup if exists.
      if [ -e ${dirBackup}.${file} ]
      then
        echo "[$config] Removing backup."
        rm -Rf ${dirBackup}.${file}
      fi
      echo "[$config] Backing up."
      mv -f ~/.$file $dirBackup
    fi

    # Symlinking.
    echo "[$config] Symlinking new config file [.$file]."
    ln -s ${dirConfig}$config/$file ~/.$file

  done  

  if [ -e ${dirConfig}$config.post ]
  then
    echo "[$config] Executing post actions."
    ( sh "${dirConfig}$config.post" )
  fi
done
