#!/bin/bash

dirDotfiles=~/.dotfiles/
dirConfig=${dirDotfiles}config/
dirBackup=${dirDotfiles}backup/
pathConfig=$1

mkdir -p $dirBackup

# For all folders that are in the config.
while read line
do
if [ -d ${dirConfig}${line} ]
then
  echo "Processing $line"
  prefix="--"
  
  if [ -e ${dirConfig}${line}.pre ]
  then
    echo "${prefix}> Execution pre actions.."
    sh "${dirConfig}${line}.pre"
  fi

  # Per file copying logic.
  for file in `ls -A ${dirConfig}${line}`
  do
    # Backup.
    echo "${prefix}> $file"
    subprefix=${prefix}--
    
    if [ -e ~/.$file -o -h ~/.$file ]
    then
      # Remove backup if exists.
      if [ -e ${dirBackup}.${file} ]
      then
        echo "${subprefix}> Removing backup"
        rm -Rf ${dirBackup}.${file}
      fi
      echo "${subprefix}> Backing up"
      mv -f ~/.$file $dirBackup
    fi

    # Symlinking.
    echo "${subprefix}> Symlinking"
    ln -s ${dirConfig}${line}/$file ~/.$file

  done  

  if [ -e ${dirConfig}${line}.post ]
  then
    echo "${prefix}> Execution post actions.."
    sh "${dirConfig}${line}.post"
  fi

fi
done < $pathConfig
echo "All dotfiles installed"
